IP2-244: registration
intive/patronage21-js-backend pull request #7
Opened 2021-04-13 13:46 UTC by Ryczko

2021-04-14 18:53 UTC, arsonx commented
Na wczorajszym spotkaniu ustaliliśmy, że @jczujko "pomoże" z refaktorem express-validator -> json-schema

2021-04-19 18:33 UTC, Kbuczynski requested changes

2021-04-19 18:33 UTC, Kbuczynski commented on swagger.json
> +                        "minLength": "Hasło musi składać się z conajmniej ośmiu znaków"
jest więcej wymogów do walidacji hasła (przykład walidacji na frontcie), dodatkowo "conajmniej" zapisuje się osobno "co najmniej"
`  
password: yup.string()
    .min(8, 'Hasło jest za krótkie - min. 8 znaków')
    .matches(/[A-Z]+/, 'Hasło musi mieć przynajmniej jedną dużą literę')
    .matches(/[!@#$%^&*()-+]+/, 'Hasło musi mieć przynajmniej jeden znak specjalny')
    .required('Wpisz hasło'),
`

2021-04-19 18:33 UTC, Kbuczynski commented on swagger.json
> +                    "type": "string"
do imienia i nazwiska jest jeszcze reguła max 20 znaków

2021-04-19 18:33 UTC, Kbuczynski commented on swagger.json
> +                    "format": "url",
tutaj żeby być spójnym z walidacją na frontcie należałoby użyć pattern'a
`
 pattern: '/((https?):\/\/)?(www.)?github.com\/[0-9a-zA-Z.-]+$/'
`

2021-04-21 09:02 UTC, Kbuczynski approved these changes

2021-04-21 09:08 UTC, merged